# Generated by Django 3.2 on 2021-06-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='is_published',
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
