# Generated by Django 3.2 on 2021-06-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210626_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(choices=[(0, 'Draft'), (1, 'Published')], default=1),
        ),
    ]
