# Generated by Django 3.2 on 2021-06-10 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210610_1639'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
