# Generated by Django 3.2 on 2021-06-12 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_boxsizes'),
        ('checkout', '0006_orderlineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
