# Generated by Django 3.2 on 2021-06-12 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_delete_boxsizes'),
        ('checkout', '0007_orderlineitem_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineItem',
            new_name='BoxItems',
        ),
    ]
