# Generated by Django 3.2 on 2021-06-12 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_rename_orderlineitem_boxitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxitems',
            options={'verbose_name_plural': 'Box Items'},
        ),
    ]
