# Generated by Django 3.2 on 2021-06-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_remove_boxitems_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boxitems',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxitems', to='checkout.order'),
        ),
    ]
