# Generated by Django 3.2 on 2021-06-10 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_boxsizes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoxSizes',
        ),
    ]
